"""
meta_orchestration/__init__.py - 元层级统一编排器

提供元模块间通信与协同机制的统一基础设施：
- 元层级统一编排器（Meta-Orchestrator）
- 元认知监控与调节系统
- 标准化通信协议
- 自我改进闭环系统
- 认知-元模块桥梁
- 统一数据格式规范
"""
from .meta_orchestrator import (
    MetaOrchestrator,
    ModuleInfo,
    TaskInfo,
    ResourceAllocation,
    TaskPriority,
    TaskStatus,
    ModuleStatus,
    get_meta_orchestrator,
)
from .module_monitor import (
    ModuleMonitor,
    MonitorMetric,
    AlertLevel,
    AlertType,
    ModuleAlert,
    MetricSample,
    ModulePerformanceSnapshot,
    AlertRule,
    AnomalyDetector,
    get_module_monitor,
)
from .communication_protocol import (
    MetaMessage,
    MetaMessageType,
    MetaResponse,
    MetaResponseStatus,
    ProtocolVersion,
    MessagePriority,
    MessageRouter,
    ProtocolStats,
    create_meta_message,
    create_meta_response,
    create_error_response,
    validate_meta_message,
)
from .self_improvement_loop import (
    SelfImprovementLoop,
    ImprovementCycle,
    ImprovementStrategy,
    ImprovementStrategyType,
    ImprovementPhase,
    ABTestConfig,
    ABTestMetrics,
    ABTestStatus,
    ABTestResult,
    MetricSnapshot,
    EvaluationMetric,
    get_self_improvement_loop,
)
from .data_contract import (
    DataContractVersion,
    EventCategory,
    EventAction,
    CognitiveEvent,
    LearningFeedback,
    DecisionFeedback,
    ParsingResult,
    ProgrammingTask,
    ModuleStatusUpdate,
    OptimizationRequest,
    OptimizationResult,
    DataContractSerializer,
    DataContractFactory,
)
from .cognitive_meta_bridge import (
    BridgeChannel,
    FeedbackTrigger,
    BridgeConfig,
    FeedbackRecord,
    CognitiveMetaBridge,
    get_cognitive_meta_bridge,
)

__all__ = [
    "MetaOrchestrator",
    "ModuleInfo",
    "TaskInfo",
    "ResourceAllocation",
    "TaskPriority",
    "TaskStatus",
    "ModuleStatus",
    "get_meta_orchestrator",
    "ModuleMonitor",
    "MonitorMetric",
    "AlertLevel",
    "AlertType",
    "ModuleAlert",
    "MetricSample",
    "ModulePerformanceSnapshot",
    "AlertRule",
    "AnomalyDetector",
    "get_module_monitor",
    "MetaMessage",
    "MetaMessageType",
    "MetaResponse",
    "MetaResponseStatus",
    "ProtocolVersion",
    "MessagePriority",
    "MessageRouter",
    "ProtocolStats",
    "create_meta_message",
    "create_meta_response",
    "create_error_response",
    "validate_meta_message",
    "SelfImprovementLoop",
    "ImprovementCycle",
    "ImprovementStrategy",
    "ImprovementStrategyType",
    "ImprovementPhase",
    "ABTestConfig",
    "ABTestMetrics",
    "ABTestStatus",
    "ABTestResult",
    "MetricSnapshot",
    "EvaluationMetric",
    "get_self_improvement_loop",
    "DataContractVersion",
    "EventCategory",
    "EventAction",
    "CognitiveEvent",
    "LearningFeedback",
    "DecisionFeedback",
    "ParsingResult",
    "ProgrammingTask",
    "ModuleStatusUpdate",
    "OptimizationRequest",
    "OptimizationResult",
    "DataContractSerializer",
    "DataContractFactory",
    "BridgeChannel",
    "FeedbackTrigger",
    "BridgeConfig",
    "FeedbackRecord",
    "CognitiveMetaBridge",
    "get_cognitive_meta_bridge",
]