import torch

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

FREE_ENERGY_THRESHOLD = 0.3
EVOLVE_TRIGGER_STEP = 200
MAX_INFERENCE_STEP = 5
NOVELTY_THRESHOLD = 0.5

MEMORY_BUFFER_SIZE = 200
KNOWLEDGE_MAX_SIZE = 1000
HISTORY_MAX_LEN = 50

LEARNING_RATE_POOL = [1e-4, 5e-4, 1e-3, 2e-3]
INITIAL_LEARNING_RATE = 1e-3

MAX_HIDDEN_DIM = 256
MIN_HIDDEN_DIM = 16
GROWTH_STEP = 8
PRUNE_STEP = 4

SAFETY_MAX_ENERGY = 10.0
SAFETY_MAX_MEMORY_GB = 4.0
SAFETY_MAX_GPU_UTIL = 0.95
SAFETY_MAX_LATENCY_MS = 1000

LOG_INTERVAL = 20
SAVE_INTERVAL = 1000
EVAL_INTERVAL = 500

STORAGE_DIR = "./data"
LOG_DIR = "./logs"
MODEL_DIR = "./models"

SEED = 42